export const helpTopics = [
  {
    id: 'start',
    icon: 'search',
    title: 'Bắt đầu',
    desc: 'Cách đưa dữ liệu vào hệ thống.',
  },
  {
    id: 'result',
    icon: 'dashboard',
    title: 'Đọc kết quả',
    desc: 'Hiểu cảm xúc, cảnh báo, từ khóa.',
  },
  {
    id: 'admin',
    icon: 'shield',
    title: 'Quản trị',
    desc: 'Dành cho admin và dữ liệu AI.',
  },
  {
    id: 'problem',
    icon: 'alert',
    title: 'Lỗi thường gặp',
    desc: 'Cách xử lý khi dữ liệu bất thường.',
  },
];

export const helpQuestions = [
  {
    id: 'url-check',
    topic: 'start',
    question: 'Kiểm tra quán bằng link như thế nào?',
    summary: 'Dán link quán để hệ thống tự thu thập và phân tích bình luận.',
    steps: [
      'Vào mục Phân tích URL.',
      'Dán link Foody hoặc Google Maps.',
      'Chọn khoảng thời gian nếu cần.',
      'Bấm Thu thập dữ liệu và chờ kết quả.',
    ],
    tip: 'Sau khi xử lý xong, dữ liệu sẽ được lưu vào Dashboard và Báo cáo.',
  },
  {
    id: 'csv-check',
    topic: 'start',
    question: 'Phân tích bằng file CSV như thế nào?',
    summary: 'Dùng file CSV để kiểm tra nhiều bình luận cùng lúc.',
    steps: [
      'Vào mục Dự đoán hàng loạt.',
      'Tải file CSV có cột bình luận.',
      'Kiểm tra bảng xem trước.',
      'Bấm Bắt đầu xử lý.',
    ],
    tip: 'Tên cột nên là content, comment, review hoặc bình luận.',
  },
  {
    id: 'data-source',
    topic: 'start',
    question: 'Hệ thống lấy dữ liệu từ đâu?',
    summary: 'Dữ liệu đến từ link quán, file CSV hoặc dữ liệu đã lưu trước đó.',
    steps: [
      'Link quán dùng để thu thập bình luận online.',
      'CSV dùng để phân tích dữ liệu có sẵn.',
      'Kết quả được lưu theo tài khoản đăng nhập.',
      'Dashboard tổng hợp lại các dữ liệu đã xử lý.',
    ],
    tip: 'Mỗi tài khoản chỉ xem dữ liệu thuộc về tài khoản đó.',
  },
  {
    id: 'sentiment-score',
    topic: 'result',
    question: 'Tỷ lệ hài lòng là gì?',
    summary: 'Là tỷ lệ bình luận được AI đánh giá là tích cực.',
    steps: [
      'Tỷ lệ cao nghĩa là quán được khen nhiều.',
      'Tỷ lệ thấp nghĩa là có nhiều phản hồi tiêu cực.',
      'Không nên chỉ nhìn mỗi con số này.',
      'Hãy xem thêm cảnh báo và từ khóa nổi bật.',
    ],
    tip: 'Một quán được khen món ăn vẫn có thể bị chê phục vụ hoặc chờ lâu.',
  },
  {
    id: 'warning-meaning',
    topic: 'result',
    question: 'Cảnh báo cần xử lý nghĩa là gì?',
    summary: 'Là nhóm bình luận có dấu hiệu tiêu cực hoặc cần chú ý.',
    steps: [
      'Xem vấn đề nào bị nhắc lại nhiều lần.',
      'Chú ý các lỗi như chờ lâu, món nguội, phục vụ kém.',
      'Một phản hồi xấu chưa chắc đáng lo.',
      'Nhiều người cùng chê một điểm thì nên cân nhắc.',
    ],
    tip: 'Cảnh báo giúp người dùng biết rủi ro trước khi đến quán.',
  },
  {
    id: 'keyword-map',
    topic: 'result',
    question: 'Bản đồ từ khóa dùng để làm gì?',
    summary: 'Giúp nhìn nhanh khách đang nhắc nhiều nhất đến điều gì.',
    steps: [
      'Từ nổi bật nghĩa là được nhắc nhiều.',
      'Từ tích cực cho biết điểm mạnh của quán.',
      'Từ tiêu cực cho biết vấn đề cần chú ý.',
      'Nên đọc cùng tỷ lệ hài lòng.',
    ],
    tip: 'Nhìn vài từ khóa lớn là có thể biết quán được khen hay chê điểm nào.',
  },
  {
    id: 'report-page',
    topic: 'result',
    question: 'Trang Báo cáo khác gì Dashboard?',
    summary: 'Dashboard xem nhanh, Báo cáo xem chi tiết hơn.',
    steps: [
      'Dashboard hiển thị tổng quan nhanh.',
      'Báo cáo hiển thị biểu đồ và xu hướng.',
      'Báo cáo phù hợp để xem sâu theo nguồn dữ liệu.',
      'Dùng Báo cáo khi cần trình bày kết quả trong đồ án.',
    ],
    tip: 'Dashboard dành cho quyết định nhanh, Báo cáo dành cho phân tích chi tiết.',
  },
  {
    id: 'worth-eat',
    topic: 'result',
    question: 'Làm sao biết quán có đáng ăn không?',
    summary: 'Xem tổng hợp tỷ lệ hài lòng, cảnh báo và từ khóa.',
    steps: [
      'Tỷ lệ hài lòng cao là tín hiệu tốt.',
      'Cảnh báo ít và không lặp lại là ổn.',
      'Từ khóa tích cực nhiều hơn tiêu cực.',
      'Đọc thêm vài bình luận tiêu biểu.',
    ],
    tip: 'Đừng quyết định chỉ dựa trên một bình luận duy nhất.',
  },
  {
    id: 'admin-feedback',
    topic: 'admin',
    question: 'Admin dùng phản hồi người dùng để làm gì?',
    summary: 'Admin xem các phản hồi AI sai để cải thiện dữ liệu huấn luyện.',
    steps: [
      'Người dùng gửi phản hồi khi AI dự đoán sai.',
      'Admin kiểm tra nội dung phản hồi.',
      'Admin duyệt hoặc từ chối phản hồi.',
      'Dữ liệu đúng có thể dùng để xuất dataset.',
    ],
    tip: 'Đây là phần giúp đồ án có hướng MLOps và cải thiện mô hình AI.',
  },
  {
    id: 'admin-user',
    topic: 'admin',
    question: 'Admin quản lý người dùng như thế nào?',
    summary: 'Admin có thể xem, lọc, khóa, mở khóa và kiểm tra trạng thái tài khoản.',
    steps: [
      'Vào mục Quản lý Người dùng.',
      'Tìm kiếm theo tên hoặc email.',
      'Xem vai trò và trạng thái hoạt động hoặc bị khóa.',
      'Thực hiện thao tác quản trị khi cần.',
    ],
    tip: 'Các thao tác quan trọng nên được ghi lại trong lịch sử hoạt động admin.',
  },
  {
    id: 'zero-result',
    topic: 'problem',
    question: 'Vì sao phân tích URL ra 0 phản hồi?',
    summary: 'Có thể chưa có bình luận mới hoặc link không đọc được.',
    steps: [
      'Link đã từng được quét nên không có dữ liệu mới.',
      'Trang không có bình luận công khai.',
      'Link bị rút gọn hoặc yêu cầu đăng nhập.',
      'Nguồn chưa được hệ thống hỗ trợ.',
    ],
    tip: 'Hãy dùng link trực tiếp của quán thay vì link rút gọn.',
  },
  {
    id: 'dashboard-late',
    topic: 'problem',
    question: 'Vì sao Dashboard chưa cập nhật ngay?',
    summary: 'Một số dữ liệu cần thời gian xử lý và lưu vào hệ thống.',
    steps: [
      'Đợi vài giây sau khi xử lý xong.',
      'Bấm làm mới dữ liệu.',
      'Kiểm tra xem có phản hồi mới không.',
      'Nếu vẫn không đổi, thử mở lại trang.',
    ],
    tip: 'File lớn hoặc URL nhiều bình luận có thể cập nhật chậm hơn.',
  },
  {
    id: 'ai-wrong',
    topic: 'problem',
    question: 'Nếu AI dự đoán sai thì làm sao?',
    summary: 'Người dùng có thể gửi phản hồi để admin kiểm tra lại.',
    steps: [
      'Mở kết quả bình luận cần góp ý.',
      'Chọn gửi phản hồi.',
      'Nhập nhãn đúng hoặc lý do.',
      'Admin sẽ kiểm tra trong trang Quản lý Phản hồi.',
    ],
    tip: 'AI có thể sai với câu mỉa mai, viết tắt hoặc bình luận quá ngắn.',
  },
];

export const helpQuickLinks = [
  {
    to: '/url-analyzer',
    label: 'Phân tích URL',
    desc: 'Dán link quán',
  },
  {
    to: '/batch-prediction',
    label: 'Phân tích CSV',
    desc: 'Tải file bình luận',
  },
  {
    to: '/dashboard',
    label: 'Dashboard',
    desc: 'Xem kết luận nhanh',
  },
  {
    to: '/report',
    label: 'Báo cáo',
    desc: 'Biểu đồ và từ khóa',
  },
  {
    to: '/compare',
    label: 'So sánh quán',
    desc: 'Đối chiếu nhiều địa điểm',
  },
];
