import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Download, Calendar, ChevronDown, RefreshCcw, CheckCircle2, Database, Smile, Frown, ShieldCheck } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { confidenceRatio, fetchUserReviews } from '../services/reviews';

export default function ReportContent() {
  const { user } = useAuth();
  const [reviews, setReviews] = useState([]);
  const load = useCallback(async () => { if (user?.id) { try { setReviews(await fetchUserReviews(user.id)); } catch (error) { window.alert(error.message); } } }, [user?.id]);
  useEffect(() => { load(); }, [load]);
  const report = useMemo(() => {
    const positive = reviews.filter((item) => Number(item.ai_label) === 1).length;
    const confidence = reviews.length ? reviews.reduce((sum, item) => sum + confidenceRatio(item.confidence), 0) / reviews.length : 0;
    const groups = {};
    reviews.forEach((item) => { const key = item.source_url === 'CSV_Upload' ? 'CSV' : item.source_url?.includes('foody') ? 'Foody' : item.source_url?.includes('shopee') ? 'Shopee' : 'Khác'; groups[key] ||= { positive: 0, negative: 0 }; groups[key][Number(item.ai_label) === 1 ? 'positive' : 'negative'] += 1; });
    return { positive, negative: reviews.length - positive, confidence, groups: Object.entries(groups) };
  }, [reviews]);
  return <div className="p-8 h-full flex flex-col space-y-6 animate-in fade-in duration-500 font-sans overflow-y-auto"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-2"><div><h1 className="text-2xl font-semibold text-white tracking-wide mb-1">Báo cáo</h1><p className="text-slate-400 text-sm">Báo cáo tổng hợp theo thời gian</p></div><button className="flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white font-medium py-2.5 px-6 rounded-xl transition-colors shadow-lg shadow-indigo-600/20"><Download className="w-4 h-4" />Xuất PDF</button></div><FilterBar onRefresh={load} /><div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><ComparisonChartCard groups={report.groups} /><WordCloudCard /></div><PerformanceSummaryCard total={reviews.length} positive={report.positive} negative={report.negative} confidence={report.confidence} /></div>;
}

function FilterBar({ onRefresh }) { return <div className="bg-slate-800/50 backdrop-blur-md border border-slate-700 rounded-2xl p-4 flex flex-col xl:flex-row xl:items-center justify-between gap-4 text-sm"><div className="flex flex-col sm:flex-row sm:items-center gap-4 text-slate-300"><div className="flex items-center gap-3"><span className="text-slate-400">Khoảng thời gian:</span><button className="flex items-center gap-2 bg-slate-900/50 border border-slate-700 hover:border-slate-500 transition-colors rounded-lg px-4 py-2"><Calendar className="w-4 h-4 text-slate-400" /><span>Toàn bộ dữ liệu</span></button></div><div className="flex items-center gap-3"><span className="text-slate-400">Nguồn:</span><button className="flex items-center gap-2 bg-slate-900/50 border border-slate-700 hover:border-slate-500 transition-colors rounded-lg px-4 py-2 min-w-[140px] justify-between"><span>Tất cả nguồn</span><ChevronDown className="w-4 h-4 text-slate-400" /></button></div></div><button onClick={onRefresh} className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors self-start xl:self-center"><RefreshCcw className="w-4 h-4" />Làm mới dữ liệu</button></div>; }

function ComparisonChartCard({ groups }) {
  const max = Math.max(1, ...groups.flatMap(([, values]) => [values.positive, values.negative]));
  return <div className="lg:col-span-2 bg-slate-800/50 backdrop-blur-md border border-slate-700 rounded-2xl p-6 flex flex-col"><div className="flex justify-between items-center mb-8"><h3 className="text-lg font-medium text-white">So sánh nền tảng</h3><div className="flex items-center gap-4 text-sm text-slate-300"><div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-emerald-500" />Tích cực</div><div className="flex items-center gap-1.5"><div className="w-2.5 h-2.5 rounded-full bg-rose-500" />Tiêu cực</div></div></div><div className="flex-1 min-h-[220px] flex items-end justify-around pb-4 pt-4 border-b border-slate-700/50 relative">{groups.map(([name, values]) => <div key={name} className="flex flex-col items-center gap-3"><div className="flex items-end gap-2 h-48"><div className="w-8 md:w-12 bg-emerald-500 rounded-t-sm transition-all hover:opacity-80" style={{ height: `${Math.max(3, values.positive / max * 100)}%` }} /><div className="w-8 md:w-12 bg-rose-500 rounded-t-sm transition-all hover:opacity-80" style={{ height: `${Math.max(3, values.negative / max * 100)}%` }} /></div><span className="text-sm font-medium text-slate-300">{name}</span></div>)}</div></div>;
}

function WordCloudCard() { return <div className="lg:col-span-1 bg-slate-800/50 backdrop-blur-md border border-slate-700 rounded-2xl p-6 flex flex-col"><h3 className="text-lg font-medium text-white mb-4">Bản đồ từ khóa</h3><div className="flex-1 bg-slate-900/50 rounded-xl border border-slate-700/50 flex flex-col items-center justify-center p-6 relative overflow-hidden min-h-[220px]"><div className="text-center space-y-3 relative z-10"><div className="text-rose-400 text-xl font-bold tracking-wide">Giao hàng chậm</div><div className="text-indigo-300 text-sm font-medium">Chất lượng tốt</div><div className="flex items-baseline justify-center gap-3"><span className="text-emerald-400 text-2xl font-bold">Đóng gói kỹ</span><span className="text-slate-200 text-base font-medium">Giá rẻ</span></div><div className="flex items-center justify-center gap-4"><span className="text-rose-500 text-lg font-bold">Tẩy chay</span><span className="text-slate-400 text-xs">Thái độ</span></div></div></div><div className="flex justify-center items-center gap-4 mt-5 text-[11px] text-slate-400"><div className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-emerald-500" />Khen ngợi</div><div className="flex items-center gap-1.5"><div className="w-2 h-2 rounded-full bg-rose-500" />Phàn nàn</div></div></div>; }

function PerformanceSummaryCard({ total, positive, negative, confidence }) { return <div className="bg-slate-800/50 backdrop-blur-md border border-slate-700 rounded-2xl p-6"><div className="flex justify-between items-center mb-6"><h2 className="text-lg font-medium text-white">Tóm tắt hiệu suất mô hình</h2><div className="flex items-center gap-1.5 px-3 py-1 bg-emerald-500/10 border border-emerald-500/20 rounded-md text-emerald-400 text-xs font-semibold tracking-wider"><CheckCircle2 className="w-3.5 h-3.5" />HOẠT ĐỘNG TỐT</div></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6"><Metric icon={Database} label="Tổng số dữ liệu" value={total} barColor="bg-indigo-400" progress={100} /><Metric icon={Smile} label="Tổng tích cực" value={positive} color="text-emerald-400" barColor="bg-emerald-500" progress={total ? positive / total * 100 : 0} glow="shadow-[0_0_8px_rgba(16,185,129,0.5)]" /><Metric icon={Frown} label="Tổng tiêu cực" value={negative} color="text-rose-400" barColor="bg-rose-500" progress={total ? negative / total * 100 : 0} glow="shadow-[0_0_8px_rgba(244,63,94,0.5)]" /><Metric icon={ShieldCheck} label="Độ tin cậy trung bình" value={`${(confidence * 100).toFixed(1)}%`} barColor="bg-indigo-400" progress={confidence * 100} /></div></div>; }
function Metric({ icon: Icon, label, value, color = 'text-white', barColor, progress, glow = '' }) { const width = Math.min(100, Math.max(0, Number(progress) || 0)); return <div className="bg-slate-900/50 border border-slate-700 rounded-xl p-5 flex flex-col justify-between"><div className="flex items-center gap-2 text-slate-400 text-xs font-medium mb-3"><Icon className="w-4 h-4" />{label}</div><div className={`text-3xl font-bold tracking-tight ${color}`}>{typeof value === 'number' ? value.toLocaleString('vi-VN') : value}</div><div className="h-1 w-full bg-slate-800 rounded-full mt-4 overflow-hidden"><div className={`h-full ${barColor} ${glow} rounded-full transition-[width] duration-700 ease-out`} style={{ width: `${width}%` }} /></div></div>; }
